server:
  port: 8080

cassandra:
  enabled: true
  embedded: false
  host: ${IP}
  keyspace: 'front50'
  cluster: 'Test Cluster'
  name: default

spinnaker:
  cassandra:
    enabled: true
    embedded: false
    cluster: 'Test Cluster'
    host: ${IP}
    keyspace: 'front50'
    name: default

redis:
  enabled: false

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*